; ***  PlatformIO Project Configuration Override File   ***
; ***  Changes done here override settings in platformio.ini    ***
;
; Place your personal settings like monitor_port and upload_port here
; instead of editing platformio.ini
; to avoid annoying merge conflicts when you pull updates into your
; personal clone of the repository
;
; Please visit documentation for the options and examples
; http://docs.platformio.org/en/stable/projectconf.html

[env]
; Specify port here. Comment out (add ; in front of line) to use auto detection.
; Under Linux, the ports are in the format /dev/tty***, typically /dev/ttyUSB0
; To look up the port, execute ls /dev/tty*, then connect the device
; then execute ls /dev/tty* again and check which device was added
;monitor_port = COM4
;upload_port = COM4


; you can define your personal board and/or settings here
; non functional example:

;[env:my_very_special_board]
;board = esp32dev
;build_flags = ${env.build_flags}
;    -DHOYMILES_PIN_MISO=1
;    -DHOYMILES_PIN_MOSI=2
;    -DHOYMILES_PIN_SCLK=3
;    -DHOYMILES_PIN_IRQ=4
;    -DHOYMILES_PIN_CE=5
;    -DHOYMILES_PIN_CS=6
;monitor_port = /dev/ttyACM0
;upload_port = /dev/ttyACM0

[env:t_connect_pro]
board = esp32-s3-devkitc-1
upload_protocol = esp-builtin
lib_extra_dirs = ../T-Connect-Pro/libraries/Arduino_GFX-1.4.6
board_build.flash_mode = qio
board_build.partitions = partitions_custom_16mb.csv
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
build_flags = ${env.build_flags}
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DOPENDTU_ETHERNET
    -DSX1262_MOSI=GPIO_NUM_11
    -DSX1262_MISO=GPIO_NUM_13
    -DSX1262_CLK=GPIO_NUM_12
    -DSX1262_CS=GPIO_NUM_14
    -DSX1262_BUSY=GPIO_NUM_38
    -DSX1262_RST=GPIO_NUM_42
    -DSX1262_IRQ=GPIO_NUM_45
    -DDISPLAY_TYPE=6U
    -DDISPLAY_DATA=GPIO_NUM_41
    -DDISPLAY_CLK=GPIO_NUM_12
    -DDISPLAY_CS=GPIO_NUM_21
    -DDISPLAY_RESET=GPIO_NUM_NC
    -DDISPLAY_MOSI=GPIO_NUM_11
    -DDISPLAY_MISO=GPIO_NUM_13
    -DDISPLAY_BL=GPIO_NUM_46
    -DDISPLAY_WIDTH=222
    -DDISPLAY_HEIGHT=480
    -DDISPLAY_OFFSET_X1=49
    -DDISPLAY_OFFSET_Y1=0
    -DDISPLAY_OFFSET_X2=49
    -DDISPLAY_OFFSET_Y2=0
    -DW5500_MOSI=GPIO_NUM_11
    -DW5500_MISO=GPIO_NUM_13
    -DW5500_SCLK=GPIO_NUM_12
    -DW5500_CS=GPIO_NUM_10
    -DW5500_INT=GPIO_NUM_9
    -DW5500_RST=GPIO_NUM_48
